AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tools/**/*'
    - 'test/**/*'
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 100

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
